### ISSUE TITLE
Oppgave 3 er ikke ferdig testet.

### ISSUE THREAD

**Issue by discoimp** [vetletj/algdat-2022-oblig-2#11]
Oppgave 3 er ikke ferdig testet. Må feilsøkes når alle metodene som den er avhengig av er ferdig.

**Comment by discoimp** [comment]
Oppgave 3 har en feil som jeg ikke finner ut av. Mulig det har med hvordan den behandler en range fra 0:0.
Jeg prioriterer å få oppg. 10 på beina før jeg går tilbake for å feilsøke.

**Comment by vetletj** [comment]
Oppgave 3 går igjennom alle tester på main branch nå - se commit for oppdateringene
